[tool.poetry]
name = "actual"
version = "0.1.0"
description = ""
authors = ["Omkar Borker <omkarborker15@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
